version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: angular-dev-app
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]